# Generated by Django 5.2 on 2025-04-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
