# Generated by Django 5.2 on 2025-04-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_requirements_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(blank=True, max_length=35)),
                ('company_name', models.CharField(max_length=100)),
                ('company_location', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address', models.CharField(blank=True, max_length=500, null=True)),
                ('students_name', models.TextField()),
            ],
        ),
    ]
