# Generated by Django 5.2 on 2025-04-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='agreement',
        ),
        migrations.AddField(
            model_name='requirements',
            name='skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
